######################################################
############### ROCKNSM Customization ################
######################################################
- name: Install ROCK NSM /etc/issue
  copy:
    src: etc-issue.in
    dest: /etc/issue.in
    mode: 0644
    owner: root
    group: root

- name: NetworkManager ROCK NSM hook
  copy:
    src: nm-issue-update
    dest: /etc/NetworkManager/dispatcher.d/50-rocknsm-issue-update
    mode: 0755
    owner: root
    group: root

- name: Install rock_status script
  template:
    src: rock_status.j2
    dest: /usr/local/bin/rock_status
    mode: 0755
    owner: root
    group: root

# main.yml - Common tasks for ROCK
- include_tasks: minimum_hardware_check.yml
- include_tasks: configure_yum_repos.yml
- include_tasks: configure_rock_repo.yml
- include_tasks: install_common_packages.yml
- include_tasks: create_rock_directories.yml
- include_tasks: disable_ipv6.yml
- include_tasks: set_hostname.yml
- include_tasks: configure_ntp.yml
- include_tasks: ensure_cache_directory_exists.yml
- include_tasks: enable_firewall.yml
- include_tasks: install_chrony.yml
