#Configure Logstash pipeline
---

# copy pipeline configuration files

- name: "Copy pipelines.yml"
  copy:
    dest: "{{ logstash_config_dir }}/pipelines.yml"
    group: 1000
    mode: u+rw,g+rw,o+r
    owner: 1000
    src: 'pipelines.yml'
  notify: 'Restart Logstash'

- name: "Copy piplines folder"
  copy:
    dest: "{{ logstash_pipeline_dir }}"
    group: 1000
    mode: u+rw,g+rw,o+r
    owner: 1000
    src: "files/pipeline/"
  notify: "Restart Logstash"

#- name: "Install Bro-Kafka configuration for Logstash"
#  copy:
#    dest: "{{ logstash_pipeline_dir }}/kafka-bro.conf"
#    group: 1000
#    mode: u+rw,g+rw,o+r
#    owner: 1000
#    src: 'logstash-kafka-bro.conf'
#  notify: "Restart Logstash"
#  when: "with_bro and with_kafka"

#- name: "Install Suricata-Kafka configuration for Logstash"
#  copy:
#    dest: "{{ logstash_pipeline_dir }}/kafka-suricata.conf"
#    group: 1000
#    mode: u+rw,g+rw,o+r
#    owner: 1000
#    src: 'logstash-kafka-suricata.conf'
#  notify: "Restart Logstash"
#  when: "with_suricata and with_kafka"

#- name: "Install FSF-Kafka configuration for Logstash"
#  copy:
#    dest: "{{ logstash_pipeline_dir }}/kafka-fsf.conf"
#    group: 1000
#    mode: u+rw,g+rw,o+r
#    owner: 1000
#    src: 'logstash-kafka-fsf.conf'
#  notify: "Restart Logstash"
#  when: "with_fsf and with_kafka"

