# site.yml is the overall playbook, but all it does is include the other playbooks that are part of the site. For more
# information about the structure see:
# http://docs.ansible.com/ansible/latest/playbooks_best_practices.html
# http://docs.ansible.com/ansible/latest/intro_inventory.html
# We follow the guidance to include naming conventions there.

---

- hosts: all

  tasks:

  # Useful for debugging, uncomment if you don't need it. This will post all
  # ansible related variables to the file /tmp/ansible.all
  #- name: Dump all vars
  #  action: template src=templates/dumpall.j2 dest=/tmp/ansible-site.all

  # When the system is run in the standalone configuration, this task will
  # add the localhost to both the servers and sensors groups
  - name: Check for local standalone installation option
    add_host:
      hostname: "{{ local_host_name }}"
      groups: servers,sensors
      ansible_connection: local
    when: standalone is defined and standalone

  - name: Check for local server installation option
    add_host:
      hostname: "{{ local_host_name }}"
      groups: servers
      ansible_connection: local
    when: serverlocal is defined and serverlocal

  - name: Check for local sensor installation option
    add_host:
      hostname: "{{ local_host_name }}"
      groups: sensors
      ansible_connection: local
    when: sensorlocal is defined and sensorlocal

- import_playbook: servers.yml
- import_playbook: sensors.yml
- import_playbook: configure_services.yml
